/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

/**
 *
 * @author hp
 */
public class HamBurger extends javax.swing.JFrame {

    /**
     * Creates new form HamBurger
     */
    public HamBurger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheeseType = new javax.swing.JComboBox<>();
        SauceType = new javax.swing.JComboBox<>();
        CartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ChickenType = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheeseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "Cheddar", "Mozzarella", "Slice", "Blue" }));
        getContentPane().add(CheeseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        SauceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "Extra Hot", "Hot ", "Medium", "Low", " " }));
        getContentPane().add(SauceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        CartButton.setText("Add to Cart");
        CartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 751, -1, -1));

        jLabel1.setText("Patty");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 43, 81, 30));

        jLabel2.setText("CheeseType");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 68, -1));

        jLabel3.setText("Spice Level");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 69, 22));

        ChickenType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "Fried ", "Grilled", "Air Fried", " ", " " }));
        ChickenType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenTypeActionPerformed(evt);
            }
        });
        getContentPane().add(ChickenType, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 99, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CartButtonActionPerformed

    private void ChickenTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenTypeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ChickenTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Burger m=new Burger();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HamBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HamBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HamBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HamBurger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HamBurger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartButton;
    private javax.swing.JComboBox<String> CheeseType;
    private javax.swing.JComboBox<String> ChickenType;
    private javax.swing.JComboBox<String> SauceType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
