/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class ChickenFajita extends javax.swing.JFrame {

    /**
     * Creates new form ChickenFajita
     */
    String ChickenType ;
    String BellPepper   ;
    String Topping   ;
    Item i=new Item();
    Pizza P = new Pizza();
    public ChickenFajita() {
        initComponents();
        setImage();
    }
    public  void ChickenFajita(Pizza p){
        
       P.PR=p.PR;
     P.name=p.name;
      P.S=p.S;
       P.quantity=p.quantity;

    }
     public String toString(){
        
        return "Pizza with specification of: "+"\nName: "+P.name+"\nSize: "+this.P.S+"\nPrice: "+this.P.PR+"\nQuantity: "+this.P.quantity+"\nChickenType: "+ this.ChickenType+"\nBellPepper: "+BellPepper+"\nTopping: "+Topping;
    }
    
     public void setImage(){
    ImageIcon IM = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/CF2.jpg"));
        Image img = IM.getImage().getScaledInstance(CF2.getWidth(), CF2.getHeight(), Image.SCALE_SMOOTH);
       CF2.setIcon(new ImageIcon(img));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        marinated = new javax.swing.JRadioButton();
        cheese = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        green = new javax.swing.JRadioButton();
        red = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        mashroom = new javax.swing.JRadioButton();
        olive = new javax.swing.JRadioButton();
        shredded = new javax.swing.JRadioButton();
        yellow = new javax.swing.JRadioButton();
        basil = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        CF2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Chicken Type : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 183, 87, 34));

        marinated.setText("Marinated");
        marinated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marinatedActionPerformed(evt);
            }
        });
        jPanel1.add(marinated, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 235, -1, -1));

        cheese.setText("Cheese");
        cheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseActionPerformed(evt);
            }
        });
        jPanel1.add(cheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 261, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setText("Bell Pepper : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 327, 103, -1));

        green.setText("Green");
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });
        jPanel1.add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        red.setText("Red");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        jPanel1.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 393, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Topping : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 464, -1, -1));

        mashroom.setText("Mashrom");
        mashroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mashroomActionPerformed(evt);
            }
        });
        jPanel1.add(mashroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 503, -1, -1));

        olive.setText("Olive");
        olive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oliveActionPerformed(evt);
            }
        });
        jPanel1.add(olive, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 529, -1, -1));

        shredded.setText("Shredded");
        shredded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shreddedActionPerformed(evt);
            }
        });
        jPanel1.add(shredded, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 287, -1, -1));

        yellow.setText("Yellow");
        yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowActionPerformed(evt);
            }
        });
        jPanel1.add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 416, -1, -1));

        basil.setText("Fresh Basil");
        basil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basilActionPerformed(evt);
            }
        });
        jPanel1.add(basil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 552, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 474, -1, -1));

        jButton2.setText("Add To Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 435, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CF2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 650, 890));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Chicken Fajita....");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseActionPerformed
        // TODO add your handling code here:
          if(cheese.isSelected()){
            shredded.setSelected(false);
            marinated.setSelected(false);
            ChickenType="Cheese";
            
        }
    }//GEN-LAST:event_cheeseActionPerformed

    private void marinatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marinatedActionPerformed
        // TODO add your handling code here:
        if(marinated.isSelected()){
            shredded.setSelected(false);
            cheese.setSelected(false);
             ChickenType="Marinated";
            
        }
    }//GEN-LAST:event_marinatedActionPerformed

    private void oliveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oliveActionPerformed
        // TODO add your handling code here:
         if(olive.isSelected()){
            mashroom.setSelected(false);
            basil.setSelected(false);
            Topping="Olive";
            
        }
    }//GEN-LAST:event_oliveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Pizza P = new Pizza();
        P.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Button b=new Button();
       i.read();
       i.write(toString());

  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void shreddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shreddedActionPerformed
        // TODO add your handling code here:
         if(shredded.isSelected()){
            marinated.setSelected(false);
            cheese.setSelected(false);
            ChickenType="Shredded";
            
        }
        
    }//GEN-LAST:event_shreddedActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        // TODO add your handling code here:
         if(green.isSelected()){
            red.setSelected(false);
            yellow.setSelected(false);
            BellPepper="Green";
        }
    }//GEN-LAST:event_greenActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // TODO add your handling code here:
         if(red.isSelected()){
            green.setSelected(false);
            yellow.setSelected(false);
            BellPepper="Red";
        }
    }//GEN-LAST:event_redActionPerformed

    private void yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowActionPerformed
        // TODO add your handling code here:
         if(yellow.isSelected()){
            green.setSelected(false);
            red.setSelected(false);
            BellPepper="Yellow";
            
        }
    }//GEN-LAST:event_yellowActionPerformed

    private void mashroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mashroomActionPerformed
        // TODO add your handling code here:
         if(mashroom.isSelected()){
            basil.setSelected(false);
            olive.setSelected(false);
             Topping="Mashrooml";
            
        }
    }//GEN-LAST:event_mashroomActionPerformed

    private void basilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basilActionPerformed
        // TODO add your handling code here:
         if(basil.isSelected()){
            mashroom.setSelected(false);
            olive.setSelected(false);
            Topping="Fresh Basil";
            
        }
    }//GEN-LAST:event_basilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChickenFajita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChickenFajita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChickenFajita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChickenFajita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChickenFajita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CF2;
    private javax.swing.JRadioButton basil;
    private javax.swing.JRadioButton cheese;
    private javax.swing.JRadioButton green;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton marinated;
    private javax.swing.JRadioButton mashroom;
    private javax.swing.JRadioButton olive;
    private javax.swing.JRadioButton red;
    private javax.swing.JRadioButton shredded;
    private javax.swing.JRadioButton yellow;
    // End of variables declaration//GEN-END:variables
}
