/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Choclate extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
     String Toppings;
    String Vessel;
    IceCream P=new IceCream();
     Item i=new Item();
    public Choclate() {
        initComponents();
        setImage();
    }
    public void chocolate(IceCream p){
        P.PR=p.PR;
     P.name=p.name;
     P.scoop=p.scoop;
     P.quantity=p.quantity;
        
    }
       public String toString(){
        
        return "Ice-Cream with specification of: "+"\nName: "+P.name+"\nScoops: "+this.P.scoop+"\nPrice: "+this.P.PR+"\nQuantity: "+this.P.quantity+"\nToppings: "+ this.Toppings+"\nIce cream Vessel: "+Vessel;
    }
    public void setImage(){
        
        ImageIcon IM = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/CCC.jpg"));
        Image img = IM.getImage().getScaledInstance(CCL.getWidth(), CCL.getHeight(), Image.SCALE_SMOOTH);
        CCL.setIcon(new ImageIcon(img));
        
//        ImageIcon IM2 = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/CCS2.jpg"));
//        Image img2 = IM2.getImage().getScaledInstance(CCS.getWidth(), CCS.getHeight(), Image.SCALE_SMOOTH);
//        CCS.setIcon(new ImageIcon(img2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        marshmello = new javax.swing.JCheckBox();
        sprinkles = new javax.swing.JCheckBox();
        cream = new javax.swing.JCheckBox();
        cup = new javax.swing.JRadioButton();
        cone = new javax.swing.JRadioButton();
        caramal = new javax.swing.JCheckBox();
        crushed = new javax.swing.JCheckBox();
        crushedcookies = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CCL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Topping : ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 67, 86, 34));

        marshmello.setText("MarshMello");
        marshmello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marshmelloActionPerformed(evt);
            }
        });
        jPanel4.add(marshmello, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 153, -1, -1));

        sprinkles.setText("Sprinkles");
        sprinkles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinklesActionPerformed(evt);
            }
        });
        jPanel4.add(sprinkles, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 153, -1, -1));

        cream.setText("Whipped cream");
        cream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creamActionPerformed(evt);
            }
        });
        jPanel4.add(cream, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        cup.setText("Cup");
        cup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupActionPerformed(evt);
            }
        });
        jPanel4.add(cup, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 503, -1, -1));

        cone.setText("Cone");
        cone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coneActionPerformed(evt);
            }
        });
        jPanel4.add(cone, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 553, -1, -1));

        caramal.setText("Caramel Sauce");
        caramal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramalActionPerformed(evt);
            }
        });
        jPanel4.add(caramal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        crushed.setText("Crushed Nuts");
        crushed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crushedActionPerformed(evt);
            }
        });
        jPanel4.add(crushed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        crushedcookies.setText("Crushed Cookies");
        crushedcookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crushedcookiesActionPerformed(evt);
            }
        });
        jPanel4.add(crushedcookies, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 153, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("IceCream Vessel");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 411, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText(" Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 70, 30));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("Add To Cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(CCL, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(306, 306, 306))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marshmelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marshmelloActionPerformed
        // TODO add your handling code here:
         if(marshmello.isSelected()){
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
              Toppings="Marshmello";
            
        }
    }//GEN-LAST:event_marshmelloActionPerformed

    private void sprinklesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinklesActionPerformed
        // TODO add your handling code here:
         if(sprinkles.isSelected()){
            marshmello.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
             Toppings="Sprinkles";
            
        }
    }//GEN-LAST:event_sprinklesActionPerformed

    private void coneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coneActionPerformed
        // TODO add your handling code here:
         if(cone.isSelected()){
            cup.setSelected(false);
            Vessel="Cone";
            
        }
    }//GEN-LAST:event_coneActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        IceCream IC = new IceCream();
        IC.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     i.read();
     i.write(toString());
        Button b=new Button();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupActionPerformed
        // TODO add your handling code here:
         if(cup.isSelected()){
            cone.setSelected(false);
             Vessel="Cup";
            
        }
    }//GEN-LAST:event_cupActionPerformed

    private void crushedcookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crushedcookiesActionPerformed
        // TODO add your handling code here:
        if(crushedcookies.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
             caramal.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
            Toppings="Crushed cookies";
            
        }
        
    }//GEN-LAST:event_crushedcookiesActionPerformed

    private void caramalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramalActionPerformed
        // TODO add your handling code here:
         if(caramal.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
              Toppings="Caramal sauce";
            
        }
    }//GEN-LAST:event_caramalActionPerformed

    private void crushedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crushedActionPerformed
        // TODO add your handling code here:
         if(crushed.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
             cream.setSelected(false);
             Toppings="Crushed Nuts";
            
        }
    }//GEN-LAST:event_crushedActionPerformed

    private void creamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creamActionPerformed
        // TODO add your handling code here:
         if(cream.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
             crushed.setSelected(false);
             Toppings="Whipped Cream";
            
        }
    }//GEN-LAST:event_creamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choclate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choclate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choclate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choclate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choclate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCL;
    private javax.swing.JCheckBox caramal;
    private javax.swing.JRadioButton cone;
    private javax.swing.JCheckBox cream;
    private javax.swing.JCheckBox crushed;
    private javax.swing.JCheckBox crushedcookies;
    private javax.swing.JRadioButton cup;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox marshmello;
    private javax.swing.JCheckBox sprinkles;
    // End of variables declaration//GEN-END:variables
}
