/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class CrownCrust extends javax.swing.JFrame {

    /**
     * Creates new form CrownCrust
     */
    Pizza P = new Pizza();

   
    String SideFilling;
    String CheeseType;
    String SauceType;

    
    Item i=new Item();
    public CrownCrust() {
        initComponents();
        setImage();
        
    }
       
    
    public  void CrownCrust(Pizza p){
        
       P.PR=p.PR;
     P.name=p.name;
      P.S=p.S;
       P.quantity=p.quantity;

    }
    public String toString(){
        
        return "Pizza with specification of: "+"\nName: "+P.name+"\nSize: "+this.P.S+"\nPrice: "+this.P.PR+"\nQuantity: "+this.P.quantity+"\nSide Filling: "+ this.SideFilling+"\nCheese Type: "+CheeseType+"\nSauce Type: "+SauceType;
    }
    public void setImage(){
    ImageIcon IM = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/CrownC.jpg"));
        Image img = IM.getImage().getScaledInstance(crownC.getWidth(), crownC.getHeight(), Image.SCALE_SMOOTH);
       crownC.setIcon(new ImageIcon(img));
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kabab = new javax.swing.JRadioButton();
        cheese = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cheddar = new javax.swing.JRadioButton();
        mozarella = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        bbq = new javax.swing.JRadioButton();
        chilligarlic = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        crownC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Side Fillings : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 183, 87, 34));

        kabab.setText("Kabab");
        kabab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kababActionPerformed(evt);
            }
        });
        jPanel1.add(kabab, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 235, -1, -1));

        cheese.setText("Cheese");
        cheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseActionPerformed(evt);
            }
        });
        jPanel1.add(cheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 261, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setText("Cheese Type : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 327, 103, -1));

        cheddar.setText("Cheddar");
        cheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheddarActionPerformed(evt);
            }
        });
        jPanel1.add(cheddar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        mozarella.setText("Mozzarella");
        mozarella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mozarellaActionPerformed(evt);
            }
        });
        jPanel1.add(mozarella, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 393, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Sauce Type : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 461, -1, -1));

        bbq.setText("BBQ");
        bbq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbqActionPerformed(evt);
            }
        });
        jPanel1.add(bbq, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        chilligarlic.setText("Chilli Garlic");
        chilligarlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chilligarlicActionPerformed(evt);
            }
        });
        jPanel1.add(chilligarlic, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 526, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 644, -1, -1));

        jButton2.setText("Add To Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 567, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(crownC, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(crownC, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 620, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Crown Crust...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1480, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseActionPerformed
        // TODO add your handling code here:
        if(cheese.isSelected()){
            kabab.setSelected(false);
            SideFilling = "Cheese";
        }

    }//GEN-LAST:event_cheeseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Pizza P = new Pizza();
        P.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
   Button b=new Button();
i.read();
i.write(toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kababActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kababActionPerformed
     
        if(kabab.isSelected()){
            cheese.setSelected(false);
            SideFilling = "Kabab";
             
        }
        
    }//GEN-LAST:event_kababActionPerformed

    private void cheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheddarActionPerformed
        // TODO add your handling code here:
         if(cheddar.isSelected()){
            mozarella.setSelected(false);
            CheeseType = "Cheddar" ;
            
        }
    }//GEN-LAST:event_cheddarActionPerformed

    private void mozarellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mozarellaActionPerformed
        // TODO add your handling code here:
        if(mozarella.isSelected()){
            cheddar.setSelected(false);
            CheeseType = "Mozarella" ;
        }
    }//GEN-LAST:event_mozarellaActionPerformed

    private void bbqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbqActionPerformed
        // TODO add your handling code here:
        if(bbq.isSelected()){
            chilligarlic.setSelected(false);
            SauceType = "BBQ" ;
        }
    }//GEN-LAST:event_bbqActionPerformed

    private void chilligarlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chilligarlicActionPerformed
        // TODO add your handling code here:
        if(chilligarlic.isSelected()){
            bbq.setSelected(false);
            SauceType = "ChilliGarlic" ;
        }
    }//GEN-LAST:event_chilligarlicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrownCrust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrownCrust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrownCrust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrownCrust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrownCrust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bbq;
    private javax.swing.JRadioButton cheddar;
    private javax.swing.JRadioButton cheese;
    private javax.swing.JRadioButton chilligarlic;
    private javax.swing.JLabel crownC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton kabab;
    private javax.swing.JRadioButton mozarella;
    // End of variables declaration//GEN-END:variables
}
