/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Image;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Pizza extends javax.swing.JFrame  implements Serializable {
      


    /**
     * Creates new form Pizza
     */
    
  Item i=new Item();
  Total t=new Total();
  
    String name ;
    int quantity ;
    int PR ;
    String S;

    
    
    public Pizza() {
        initComponents();
        
        setImage();
    }
    
    public String toString(){
     
        return "\nName: "+name+"\nSize: "+S+"\nPrice: "+PR+"\nQuantity:  "+quantity ;
    }
 
                 
  
     
    
 public void setImage(){
        
        ImageIcon IM = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/CC.jpg"));
        Image img = IM.getImage().getScaledInstance(CC.getWidth(), CC.getHeight(), Image.SCALE_SMOOTH);
        CC.setIcon(new ImageIcon(img));
        
        ImageIcon IM2 = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/CF.jpg"));
        Image img2 = IM2.getImage().getScaledInstance(CF.getWidth(), CF.getHeight(), Image.SCALE_SMOOTH);
        CF.setIcon(new ImageIcon(img2));

        
        ImageIcon IM3 = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/PP.jpg"));
        Image img3 = IM3.getImage().getScaledInstance(PP.getWidth(), PP.getHeight(), Image.SCALE_SMOOTH);
        PP.setIcon(new ImageIcon(img3));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Pepproni = new javax.swing.JButton();
        N3 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        Q3 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        S3 = new javax.swing.JComboBox<>();
        PP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        CrownCrust = new javax.swing.JButton();
        N = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        QS = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        Size = new javax.swing.JComboBox<>();
        CC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ChickenFajita = new javax.swing.JButton();
        N2 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        Q2 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        S2 = new javax.swing.JComboBox<>();
        CF = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setText("Name :");

        jLabel5.setText("Price : ");

        jLabel6.setText("Quantity : ");

        jButton1.setText("Customize");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Pepproni.setText("Add To Cart");
        Pepproni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepproniActionPerformed(evt);
            }
        });

        N3.setText("Pepproni");

        P3.setText("8");

        Q3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jLabel17.setText("Size : ");

        S3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "small", "Medium", "Large", "ExtraLarge" }));
        S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pepproni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P3)
                            .addComponent(N3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))))
            .addComponent(PP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(PP, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(N3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(P3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pepproni)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 207, -1, 458));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PIZZA...");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 1162, 28));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Name :");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 296, 51, -1));

        jLabel20.setText("Price : ");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 328, -1, -1));

        jLabel21.setText("Quantity : ");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 363, -1, -1));

        jButton7.setText("Customize");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 421, -1, -1));

        CrownCrust.setText("Add To Cart");
        CrownCrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrownCrustActionPerformed(evt);
            }
        });
        jPanel10.add(CrownCrust, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 421, -1, -1));

        N.setText("Crown Crust");
        jPanel10.add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 296, 79, 21));

        price.setText("7");
        jPanel10.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 328, -1, -1));

        QS.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jPanel10.add(QS, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 360, -1, -1));

        jLabel1.setText("Size : ");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 394, -1, -1));

        Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "small", "Medium", "Large", "ExtraLarge" }));
        Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeActionPerformed(evt);
            }
        });
        jPanel10.add(Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 391, -1, -1));
        jPanel10.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 314, 267));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 450));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 55, 6, 440));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 132, 6, 692));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setText("Name :");

        jLabel8.setText("Price : ");

        jLabel9.setText("Quantity : ");

        jButton3.setText("Customize");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ChickenFajita.setText("Add To Cart");
        ChickenFajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenFajitaActionPerformed(evt);
            }
        });

        N2.setText("Chicken Fajita");

        P2.setText("6");

        Q2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel16.setText("Size : ");

        S2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|", "small", "Medium", "Large", "ExtraLarge" }));
        S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S2ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P2)
                            .addComponent(N2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChickenFajita))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(CF, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(CF, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(N2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(P2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChickenFajita)
                            .addComponent(jButton3))
                        .addContainerGap())
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 207, 340, 458));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1484, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pizza P = new Pizza();
        P.name = N3.getText();
        P.quantity = (int)Q3.getValue();
        P.S = (String)S3.getSelectedItem();
        P.PR = Integer.parseInt(P3.getText());
        int i=(P.PR)*(P.quantity);
        t.read();
        t.write(i);
        Pepproni P1 = new Pepproni();
        P1.Pepproni(P);
        P1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PepproniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepproniActionPerformed
        // TODO add your handling code here:
        Button b=new Button();
        Pizza P = new Pizza();
        P.name = N3.getText();
        P.quantity = (int)Q3.getValue();
        P.S = (String)S3.getSelectedItem();
        P.PR = Integer.parseInt(P3.getText());
        
        int i=(P.PR)*(P.quantity);
        t.read();
        t.write(i);
        P.i.read();
        P.i.write(P.toString());
    
    }//GEN-LAST:event_PepproniActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        // TODO add your handling code here:
        Pizza P = new Pizza();
        P.name = N.getText();
        P.quantity = (int)QS.getValue();
        P.S = (String)Size.getSelectedItem();
        P.PR = Integer.parseInt(price.getText());
        int i=(P.PR)*(P.quantity);
        
        t.read();
        t.write(i);
      
        
        CrownCrust C1 = new CrownCrust();
        C1.CrownCrust(P);
        C1.setVisible(true);
//        L.add(C1);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void CrownCrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrownCrustActionPerformed
        // TODO add your handling code here:
        
        Pizza P = new Pizza();
        P.name = N.getText();
        P.S  = (String)Size.getSelectedItem();
        P.quantity = (int)QS.getValue();
        P.PR = Integer.parseInt(price.getText());
        int i=(P.PR)*(P.quantity);
        t.read();
        t.write(i);
        P.i.read();
        P.i.write(P.toString());
       Button b=new Button();
        
        
    }//GEN-LAST:event_CrownCrustActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      Pizza P = new Pizza();
        P.name = N2.getText();
        P.quantity = (int)Q2.getValue();
        P.S = (String)S2.getSelectedItem();
        P.PR = Integer.parseInt(P2.getText());
         int i=(P.PR)*(P.quantity);
        t.read();
        t.write(i);
       
        
        ChickenFajita C1 = new ChickenFajita();
        C1.ChickenFajita(P);
        C1.setVisible(true);
//        L.add(C1);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ChickenFajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenFajitaActionPerformed
        // TODO add your handling code here:
        Button b=new Button();
        Pizza P = new Pizza();
        P.name = N2.getText();
        P.quantity = (int)Q2.getValue();
        P.S = (String)S2.getSelectedItem();
        P.PR = Integer.parseInt(P2.getText());
         int i=(P.PR)*(P.quantity);
     t.read();
        t.write(i);

         P.i.read();
   P.i.write(P.toString());

        
      
    }//GEN-LAST:event_ChickenFajitaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menuu m=new Menuu();
        m.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeActionPerformed
        // TODO add your handling code here:
        if(Size.getSelectedItem().equals("Large")){
            price.setText("10");
        }
        else if(Size.getSelectedItem().equals("Medium")){
            price.setText("8");
        }
        else if(Size.getSelectedItem().equals("ExtraLarge")){
            price.setText("12");
        }
        else{
            price.setText("7");
        }
    }//GEN-LAST:event_SizeActionPerformed

    private void S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2ActionPerformed
        // TODO add your handling code here:
        
         if(S2.getSelectedItem().equals("Large")){
            P2.setText("11");
        }
        else if(S2.getSelectedItem().equals("Medium")){
            P2.setText("7");
        }
        else if(S2.getSelectedItem().equals("ExtraLarge")){
            P2.setText("11");
        }
        else{
            P2.setText("6");
        }
    }//GEN-LAST:event_S2ActionPerformed

    private void S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3ActionPerformed
        // TODO add your handling code here:
        if(S3.getSelectedItem().equals("Large")){
            P3.setText("10");
        }
        else if(S3.getSelectedItem().equals("Medium")){
            P3.setText("8");
        }
        else if(S3.getSelectedItem().equals("ExtraLarge")){
            P3.setText("13");
        }
        else{
            P3.setText("7");
        }
    }//GEN-LAST:event_S3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CC;
    private javax.swing.JLabel CF;
    private javax.swing.JButton ChickenFajita;
    private javax.swing.JButton CrownCrust;
    private javax.swing.JLabel N;
    private javax.swing.JLabel N2;
    private javax.swing.JLabel N3;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel PP;
    private javax.swing.JButton Pepproni;
    private javax.swing.JSpinner Q2;
    private javax.swing.JSpinner Q3;
    private javax.swing.JSpinner QS;
    private javax.swing.JComboBox<String> S2;
    private javax.swing.JComboBox<String> S3;
    private javax.swing.JComboBox<String> Size;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
