/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Vanilla extends javax.swing.JFrame {

    /**
     * Creates new form Vanilla
     */
     IceCream P=new IceCream();
    Item i=new Item();
    String Toppings;
    String Vessel;
    public Vanilla() {
        initComponents();
        setImage();
    }
     public String toString(){
        
        return "Ice-Cream with specification of: "+"\nName: "+P.name+"\nScoops: "+this.P.scoop+"\nPrice: "+this.P.PR+"\nQuantity: "+this.P.quantity+"\nToppings: "+ this.Toppings+"\nIce cream Vessel: "+Vessel;
    }
     public  void Vanilla(IceCream p){
        
     P.PR=p.PR;
     P.name=p.name;
     P.scoop=p.scoop;
     P.quantity=p.quantity;

    }
    
    public void setImage(){
        
        ImageIcon IM = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/ST.jpg"));
        Image img = IM.getImage().getScaledInstance(STS.getWidth(), STS.getHeight(), Image.SCALE_SMOOTH);
        STS.setIcon(new ImageIcon(img));
        
        ImageIcon IM2 = new  ImageIcon(getClass().getResource("/foodorderingsystem/Pics/ST2.jpg"));
        Image img2 = IM2.getImage().getScaledInstance(ST2.getWidth(), ST2.getHeight(), Image.SCALE_SMOOTH);
        ST2.setIcon(new ImageIcon(img2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ST2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        marshmello = new javax.swing.JCheckBox();
        sprinkles = new javax.swing.JCheckBox();
        cream = new javax.swing.JCheckBox();
        cup = new javax.swing.JRadioButton();
        cone = new javax.swing.JRadioButton();
        caramal = new javax.swing.JCheckBox();
        crushed = new javax.swing.JCheckBox();
        crushedcookies = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        STS = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ST2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ST2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 43, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Topping : ");

        marshmello.setText("MarshMello");
        marshmello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marshmelloActionPerformed(evt);
            }
        });

        sprinkles.setText("Sprinkles");
        sprinkles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinklesActionPerformed(evt);
            }
        });

        cream.setText("Whipped cream");
        cream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creamActionPerformed(evt);
            }
        });

        cup.setText("Cup");
        cup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupActionPerformed(evt);
            }
        });

        cone.setText("Cone");
        cone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coneActionPerformed(evt);
            }
        });

        caramal.setText("Caramel Sauce");
        caramal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramalActionPerformed(evt);
            }
        });

        crushed.setText("Crushed Nuts");
        crushed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crushedActionPerformed(evt);
            }
        });

        crushedcookies.setText("Crushed Cookies");
        crushedcookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crushedcookiesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("IceCream Vessel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(STS, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Add To Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caramal)
                            .addComponent(marshmello)
                            .addComponent(jLabel3))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sprinkles)
                                    .addComponent(crushed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crushedcookies)
                                    .addComponent(cream))
                                .addGap(70, 70, 70))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cup)
                                    .addComponent(cone)
                                    .addComponent(jButton1))))
                        .addContainerGap(253, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cream)
                    .addComponent(marshmello)
                    .addComponent(sprinkles))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caramal)
                    .addComponent(crushed)
                    .addComponent(crushedcookies))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cup)
                        .addGap(27, 27, 27)
                        .addComponent(cone)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 43, -1, 582));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void marshmelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marshmelloActionPerformed
        // TODO add your handling code here:
         if(marshmello.isSelected()){
            cream.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
             crushed.setSelected(false);
              Toppings="Marshmello";
            
        }
    }//GEN-LAST:event_marshmelloActionPerformed

    private void sprinklesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinklesActionPerformed
        // TODO add your handling code here:
        if(sprinkles.isSelected()){
            marshmello.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
             Toppings="Sprinkles";
            
        }
    }//GEN-LAST:event_sprinklesActionPerformed

    private void coneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coneActionPerformed
        // TODO add your handling code here:
         if(cone.isSelected()){
            cup.setSelected(false);
            Vessel="Cone";
            
        }
    }//GEN-LAST:event_coneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        IceCream IC = new IceCream();
        IC.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
i.read();
        i.write(toString());
        Button b=new Button();
// TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void creamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creamActionPerformed
        // TODO add your handling code here:
        if(cream.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
             crushed.setSelected(false);
             Toppings="Whipped Cream";
            
        }
    }//GEN-LAST:event_creamActionPerformed

    private void caramalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramalActionPerformed
        // TODO add your handling code here:
         if(caramal.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
             Toppings="Caramal sauce";
            
        }
    }//GEN-LAST:event_caramalActionPerformed

    private void crushedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crushedActionPerformed
        // TODO add your handling code here:
        if(crushed.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
            crushedcookies.setSelected(false);
            caramal.setSelected(false);
             cream.setSelected(false);
             Toppings="Crushed Nuts"; 
             
            
        }
    }//GEN-LAST:event_crushedActionPerformed

    private void crushedcookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crushedcookiesActionPerformed
        // TODO add your handling code here:
        if(crushedcookies.isSelected()){
            marshmello.setSelected(false);
            sprinkles.setSelected(false);
             caramal.setSelected(false);
            crushed.setSelected(false);
             cream.setSelected(false);
             Toppings="Crushed cookies";
           
            
        }
    }//GEN-LAST:event_crushedcookiesActionPerformed

    private void cupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupActionPerformed
        // TODO add your handling code here:
         if(cup.isSelected()){
            cone.setSelected(false);
              Vessel="Cup";
            
        }
    }//GEN-LAST:event_cupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ST2;
    private javax.swing.JLabel STS;
    private javax.swing.JCheckBox caramal;
    private javax.swing.JRadioButton cone;
    private javax.swing.JCheckBox cream;
    private javax.swing.JCheckBox crushed;
    private javax.swing.JCheckBox crushedcookies;
    private javax.swing.JRadioButton cup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox marshmello;
    private javax.swing.JCheckBox sprinkles;
    // End of variables declaration//GEN-END:variables
}
